name: easy_loader_plus
description: A modern, interactive, and progress-aware loading indicator for Flutter, designed as a spiritual successor to flutter_easyloading.
version: 0.0.3
homepage: https://github.com/Arpit980jai/easy_loader_plus
repository: https://github.com/Arpit980jai/easy_loader_plus
issue_tracker: https://github.com/Arpit980jai/easy_loader_plus/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/promo.png
